# Generated by Django 3.1.7 on 2021-07-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollee',
            table='enrollee',
        ),
    ]
