# Generated by Django 3.1.7 on 2021-07-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0002_auto_20210725_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollee',
            name='year_level',
        ),
        migrations.AddField(
            model_name='enrollee',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
