# Generated by Django 3.1.7 on 2021-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0003_auto_20210726_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
