# Generated by Django 3.1.7 on 2021-10-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0007_auto_20211021_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollee.program'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollee.strand'),
        ),
    ]
