# Generated by Django 3.1.7 on 2021-10-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0011_strand'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollee.strand'),
        ),
    ]
