# Generated by Django 3.1.7 on 2021-10-20 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0013_auto_20211021_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollee.strand'),
        ),
        migrations.AlterField(
            model_name='strand',
            name='strand_id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strand',
            name='track',
            field=models.CharField(max_length=100),
        ),
    ]
