# Generated by Django 3.1.7 on 2021-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0014_auto_20211021_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strand',
            name='strand_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strand',
            name='track',
            field=models.CharField(max_length=70),
        ),
    ]
