# Generated by Django 3.1.7 on 2021-12-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0019_enrollee_enrolled_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=None)),
                ('enrollee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollee.enrollee')),
            ],
            options={
                'db_table': 'exam_answers',
            },
        ),
    ]
