# Generated by Django 3.1.7 on 2021-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0023_auto_20211205_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
