# Generated by Django 3.1.7 on 2021-12-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20211129_2317'),
        ('enrollee', '0024_auto_20211205_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.question'),
        ),
    ]
