# Generated by Django 3.1.7 on 2021-12-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0025_auto_20211205_1919'),
        ('enrollee', '0025_auto_20211206_0027'),
    ]

    operations = [
    ]
