# Generated by Django 3.1.7 on 2021-12-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0026_merge_20211206_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresults',
            name='part',
        ),
        migrations.AlterField(
            model_name='examanswers',
            name='answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='enrollee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollee.enrollee'),
        ),
    ]
