# Generated by Django 4.0 on 2022-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0029_alter_enrollee_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='static/facerec_assets/images/'),
        ),
    ]
