# Generated by Django 4.0 on 2022-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0030_alter_enrollee_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='pictures',
            field=models.ImageField(default='missing_profile.jpg', upload_to='static/profilephotos/'),
        ),
    ]
