# Generated by Django 4.0 on 2022-02-15 04:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0035_alter_enrollee_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='C:\\Users\\John Paul Alferez\\OneDrive\\Documents\\IT Stuff\\GitHub\\EURIQA\\EURIQA\\static2\\facerec_assets/images')),
        ),
    ]
