# Generated by Django 4.0 on 2022-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0037_alter_enrollee_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='face_references/'),
        ),
    ]
