# Generated by Django 3.1.7 on 2021-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0005_auto_20211021_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=70)),
                ('college', models.CharField(max_length=70)),
                ('num_enrollees', models.IntegerField()),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('strand_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('strand_name', models.CharField(max_length=70)),
                ('track', models.CharField(max_length=70)),
                ('num_enrollees', models.IntegerField()),
            ],
            options={
                'db_table': 'strand',
            },
        ),
        migrations.RemoveField(
            model_name='enrollee',
            name='program',
        ),
        migrations.RemoveField(
            model_name='enrollee',
            name='strand',
        ),
    ]
