# Generated by Django 3.1.7 on 2021-10-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0017_auto_20211021_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollee.program'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='strand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollee.strand'),
        ),
    ]
