# Generated by Django 3.1.7 on 2021-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0018_auto_20211021_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='enrolled_as',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
