# Generated by Django 3.1.7 on 2021-12-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20211129_2317'),
        ('enrollee', '0020_examanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(default=0)),
                ('enrollee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollee.enrollee')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.exam')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.part')),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
    ]
