# Generated by Django 3.1.7 on 2021-12-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0024_auto_20211205_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='answer',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
