# Generated by Django 4.0 on 2021-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0027_auto_20211206_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='static/faces'),
        ),
    ]
