# Generated by Django 3.1.7 on 2021-09-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='department',
            new_name='position',
        ),
    ]
