# Generated by Django 3.1.7 on 2021-11-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='ques_points',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
