# Generated by Django 3.1.7 on 2021-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_part_ques_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
