# Generated by Django 3.1.7 on 2021-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_exam_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='link',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
