# Generated by Django 3.1.7 on 2021-11-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20211107_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='ques_points',
        ),
    ]
