# Generated by Django 3.1.7 on 2021-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_part_ques_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='picture',
            field=models.FileField(null=True, upload_to='static2'),
        ),
    ]
