# Generated by Django 3.1.7 on 2021-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_administrator_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='total_items',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
